-- Create tables for vulnerability management pipeline
-- All tables use IF NOT EXISTS to allow safe re-execution

-- ============================================================================
-- Raw Data Tables
-- ============================================================================

-- CVE (Common Vulnerabilities and Exposures) raw data
CREATE TABLE IF NOT EXISTS raw_cve (
    cve_id TEXT PRIMARY KEY,
    published_date DATE,
    cvss_score NUMERIC,
    severity TEXT,
    description TEXT,
    source_json TEXT,
    ingested_at TIMESTAMP
);

-- KEV (Known Exploited Vulnerabilities) raw data
CREATE TABLE IF NOT EXISTS raw_kev (
    cve_id TEXT,
    date_added DATE,
    due_date DATE,
    vendor TEXT,
    product TEXT,
    source_json TEXT,
    ingested_at TIMESTAMP,
    PRIMARY KEY (cve_id)
);

-- EPSS (Exploit Prediction Scoring System) raw data
CREATE TABLE IF NOT EXISTS raw_epss (
    cve_id TEXT,
    epss_date DATE,
    epss_score NUMERIC,
    percentile NUMERIC,
    source_json TEXT,
    ingested_at TIMESTAMP,
    PRIMARY KEY (cve_id, epss_date)
);

-- ============================================================================
-- Report Tables
-- ============================================================================

-- Daily CVE report with aggregated metrics
CREATE TABLE IF NOT EXISTS report_cve_daily (
    as_of_date DATE,
    cve_id TEXT,
    severity TEXT,
    cvss_score NUMERIC,
    is_kev BOOLEAN,
    epss_score NUMERIC,
    age_days INT,
    risk_score NUMERIC,
    vendor TEXT,
    product TEXT,
    PRIMARY KEY (as_of_date, cve_id)
);

-- Daily product report with aggregated metrics per vendor/product
CREATE TABLE IF NOT EXISTS report_product_daily (
    as_of_date DATE,
    vendor TEXT,
    product TEXT,
    open_vulns INT,
    high_crit_count INT,
    kev_count INT,
    avg_epss NUMERIC,
    avg_risk_score NUMERIC,
    PRIMARY KEY (as_of_date, vendor, product)
);

-- ============================================================================
-- Alerting Table
-- ============================================================================

-- Alerts generated by the alerting system
CREATE TABLE IF NOT EXISTS alerts (
    created_at TIMESTAMP,
    alert_type TEXT,
    scope TEXT,
    message TEXT,
    severity TEXT,
    metric_value NUMERIC
);
